/**
 * MPP attribution memo encoding for TIP-20 `transferWithMemo`.
 *
 * When no user-provided memo is present, the SDK auto-generates an
 * attribution memo so MPP transactions are identifiable on-chain.
 *
 * ## Byte Layout (32 bytes)
 *
 * | Offset | Size | Field                                     |
 * |--------|------|-------------------------------------------|
 * | 0..3   | 4    | TAG = keccak256("mpp")[0..3]               |
 * | 4      | 1    | version (0x01)                            |
 * | 5..14  | 10   | serverId = keccak256(serverId)[0..9]       |
 * | 15..24 | 10   | clientId = keccak256(clientId)[0..9] or 0s |
 * | 25..31 | 7    | nonce = keccak256(challengeId)[0..6]      |
 *
 * The TAG prefix makes MPP transactions trivially distinguishable
 * from arbitrary memos via `TransferWithMemo` event topic filtering.
 *
 * @module
 */
/** First 4 bytes of keccak256("mpp") — the on-chain MPP tag. */
export declare const tag: `0x${string}`;
/** 10 zero bytes representing an anonymous (no clientId) client. */
export declare const anonymous: "0x00000000000000000000";
/**
 * Encodes an MPP attribution memo as a `bytes32` hex string.
 *
 * @param parameters - The serverId (server identity) and optional clientId.
 * @returns A `0x`-prefixed 64-char hex string (32 bytes).
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode({ challengeId: 'challenge-123', clientId: 'my-app', serverId: 'api.example.com' })
 * ```
 */
export declare function encode(parameters: encode.Parameters): `0x${string}`;
export declare namespace encode {
    type Parameters = {
        /** Challenge ID used to derive a deterministic nonce, binding the memo to the challenge. */
        challengeId: string;
        /** Optional client identity used to derive the client fingerprint. */
        clientId?: string | undefined;
        /** Server identity used to derive the server fingerprint. */
        serverId: string;
    };
}
/**
 * Checks whether a memo was generated by the MPP attribution system.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns `true` if the memo starts with the MPP tag and version byte.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * Attribution.isMppMemo(Attribution.encode({ challengeId: 'challenge-123', serverId: 'api.example.com' })) // true
 * Attribution.isMppMemo('0x0000...0000')      // false
 * ```
 */
export declare function isMppMemo(memo: `0x${string}`): boolean;
/**
 * Verifies that a memo's server fingerprint matches the given serverId.
 *
 * Checks TAG, version byte, and that bytes 5–14 equal keccak256(serverId)[0..9].
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @param serverId - The expected server identity.
 * @returns `true` if the memo has a valid MPP tag and matching server fingerprint.
 */
export declare function verifyServer(memo: `0x${string}`, serverId: string): boolean;
/**
 * Decodes an MPP attribution memo into its constituent parts.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns The decoded fields, or `null` if the memo is not an MPP memo.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode({ challengeId: 'challenge-123', clientId: 'my-app', serverId: 'api.example.com' })
 * const decoded = Attribution.decode(memo)
 * // { version: 1, serverFingerprint: '0x...', clientFingerprint: '0x...', nonce: '0x...' }
 * ```
 */
export declare function decode(memo: `0x${string}`): decode.Result | null;
export declare namespace decode {
    type Result = {
        /** Memo version (currently always 1). */
        version: number;
        /** 10-byte server fingerprint hex (keccak256(serverId)[0..9]). */
        serverFingerprint: `0x${string}`;
        /** 10-byte client fingerprint hex, or `null` if anonymous. */
        clientFingerprint: `0x${string}` | null;
        /** 7-byte challenge-bound nonce hex (keccak256(challengeId)[0..6]). */
        nonce: `0x${string}`;
    };
}
/**
 * Computes the 7-byte challenge-bound nonce: keccak256(challengeId)[0..6].
 * @internal
 */
export declare function challengeNonce(challengeId: string): Uint8Array;
/**
 * Verifies that a memo's nonce is bound to the given challengeId.
 *
 * Checks TAG, version byte, and that bytes 25–31 equal keccak256(challengeId)[0..6].
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @param challengeId - The expected challenge ID.
 * @returns `true` if the memo has a valid MPP tag and matching challenge nonce.
 */
export declare function verifyChallengeBinding(memo: `0x${string}`, challengeId: string): boolean;
//# sourceMappingURL=Attribution.d.ts.map