"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.setSrcsetAttribute = exports.getSrcsetAttribute = exports.generateImgAttrs = exports.resizeImage = exports.isUnsplashImage = exports.isLocalContentImage = exports.hbs = exports.getAvailableImageWidths = exports.dedent = void 0;
var dedent_js_1 = require("./dedent.js");
Object.defineProperty(exports, "dedent", { enumerable: true, get: function () { return __importDefault(dedent_js_1).default; } });
var get_available_image_widths_js_1 = require("./get-available-image-widths.js");
Object.defineProperty(exports, "getAvailableImageWidths", { enumerable: true, get: function () { return __importDefault(get_available_image_widths_js_1).default; } });
var hbs_js_1 = require("./hbs.js");
Object.defineProperty(exports, "hbs", { enumerable: true, get: function () { return __importDefault(hbs_js_1).default; } });
var is_local_content_image_js_1 = require("./is-local-content-image.js");
Object.defineProperty(exports, "isLocalContentImage", { enumerable: true, get: function () { return __importDefault(is_local_content_image_js_1).default; } });
var is_unsplash_image_js_1 = require("./is-unsplash-image.js");
Object.defineProperty(exports, "isUnsplashImage", { enumerable: true, get: function () { return __importDefault(is_unsplash_image_js_1).default; } });
var resize_image_js_1 = require("./resize-image.js");
Object.defineProperty(exports, "resizeImage", { enumerable: true, get: function () { return __importDefault(resize_image_js_1).default; } });
var generate_img_attrs_js_1 = require("./generate-img-attrs.js");
Object.defineProperty(exports, "generateImgAttrs", { enumerable: true, get: function () { return __importDefault(generate_img_attrs_js_1).default; } });
var srcset_attribute_js_1 = require("./srcset-attribute.js");
Object.defineProperty(exports, "getSrcsetAttribute", { enumerable: true, get: function () { return srcset_attribute_js_1.getSrcsetAttribute; } });
Object.defineProperty(exports, "setSrcsetAttribute", { enumerable: true, get: function () { return srcset_attribute_js_1.setSrcsetAttribute; } });
